= snob(1)
Lewis E. Bogan
:email: <lewis.bogan@comcast.net>
:date: {localdate}
:doctype: manpage
:mansource: snob {shards_version}
:manmanual: Snob Manual
:man-linkstyle: pass:[blue R < >]
:shards_version: {shards_version}

== name
snob - snob network object browser

== synopsis
*snob* [OPTIONS] [HOST]

== description
*snob* uses the snmpwalk utility to browse MIB objects on snmp-enabled devices, such as, 
switches, routers, servers, etc.

This utility is written specifically for snmp version 3 because of
its security features. Backwards compatibility to version 2c is not included
at this time. Sorry:(.

The special *--list* switch is included to provide easily remembered names for
1.0.8802.1.1.2.1.4.1.1.9 or ipNetToPhysicalPhysAddress or other cryptic looking
OIDs.

The output is raw by default. In addition, a *--dump* option is included for dumping
the resulting output to a file, raw_dump.txt, for later perusal. A *--format* option
exists in an attempt to pretty-print the output for display on screen. The *--only-values*
flag allows output to be used raw by another application like RRDTool for graphing 
trends when you know which OID you want.

For ease of use, a *--edit* option is included for editing the config file.

== options
*-d, --dump*::
        writes output to a file, raw only by default

*-e, --edit*::
        edits global config file using default editor specified by the _EDITOR_
        environment variable.

*-f, --formatted*::
        displays output as a formatted table

*-l, --list*::
        displays some predefined OID's (Object IDentifiers)

*-m OID, --mib*=_OID_::
        displays information for this OID
        (default system)

*-o, --only-values*::
        displays values only (not OID = value)

== general options
*-h, --help*::
        show this help  

*-v, --version*::
        show version  

== examples
----
$ snob myserver  
sysDescr.0 = Linux myserver 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64  
sysObjectID.0 = netSnmpAgentOIDs.10  
sysUpTimeInstance = 9:0:58:49.85  
sysContact.0 = root  
sysName.0 = myserver  
sysLocation.0 = my space  
sysServices.0 = 76  
sysORLastChange.0 = 0:0:00:15.09  
sysServices.0 = 76  
sysORLastChange.0 = 0:0:00:15.09  
----

== files
pass:[~/.snob/snobrc.yml]::
Main configuration file located in the user's home directory.

pass:[~/tmp/raw_dump.txt]::
Unformatted dump of tree data.


== see also
snmpwalk(1), snobrc.yml(5)

== copyright
Copyright (C) {localyear} {author}. +

http://opensource.org/licenses/MIT[License MIT]

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
